# Generated by Django 4.2.1 on 2023-06-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_logger'),
    ]

    operations = [
        migrations.AddField(
            model_name='logger',
            name='fname',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logger',
            name='name',
            field=models.CharField(default='10:10', max_length=50),
            preserve_default=False,
        ),
    ]
