# Generated by Django 4.2.1 on 2023-06-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0006_logger_fname_logger_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('guest_count', models.IntegerField()),
                ('reservation_date', models.DateField(auto_now=True)),
                ('comments', models.CharField(max_length=100)),
            ],
        ),
    ]
